version: '3.1'
services:
  API:
    container_name: ramarket-springboot-postgresql
    image: ramarket-springboot-postgresql
    build: ./
    ports:
      - "80:80"
    depends_on:
      - PostgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/ramarket_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always

  PostgreSQL:
    container_name: ramarket-postgres
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ramarket_db
    restart: always